name: "Daily Build"

on:
    schedule:
        - cron: '0 0 * * *'

jobs:
    build:
        name: Build Cyanide Daily
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.9'
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install poetry
            - name: Build package
              run: poetry build
            - name: Upload artifacts
              uses: actions/upload-artifact@v1
              with:
                name: dist
                path: ./dist
